// // import 'dart:io';
// // import 'package:firebase_storage/firebase_storage.dart';
// // import 'package:flutter/material.dart';
// // import 'package:image_picker/image_picker.dart';
// // import 'package:cloud_firestore/cloud_firestore.dart';
// // import 'package:judging_app/models/Athlete.dart';

// // class AddAthleteScreen extends StatefulWidget {
// //   @override
// //   _AddAthleteScreenState createState() => _AddAthleteScreenState();
// // }

// // class _AddAthleteScreenState extends State<AddAthleteScreen> {
// //   final _formKey = GlobalKey<FormState>();
// //   final ImagePicker _picker = ImagePicker();
// //   File? _imageFile;
// //   TextEditingController _firstNameController = TextEditingController();
// //   TextEditingController _lastNameController = TextEditingController();
// //   TextEditingController _nationalIdController = TextEditingController();
// //   TextEditingController _phoneNumberController = TextEditingController();
// //   TextEditingController _ageController = TextEditingController();
// //   String _gender = 'Male';


// //   Future<void> _pickImage() async {
// //     final pickedFile = await _picker.pickImage(source: ImageSource.gallery);
// //     setState(() {
// //       if (pickedFile != null) {
// //         _imageFile = File(pickedFile.path);
// //       } else {
// //         print('No image selected.');
// //       }
// //     });
// //   }

// //  Future<String> _uploadImage(File image) async {
// //   try {
// //     String uploadPath = 'athlete_images/${DateTime.now().toString()}.jpg';
// //     Reference ref = FirebaseStorage.instance.ref().child(uploadPath);
// //     await ref.putFile(image);
// //     return await ref.getDownloadURL();
// //   } catch (e) {
// //     print("Failed to upload image: $e");
// //     return '';  // Return an empty string or handle differently
// //   }
// // }

// // Future<void> _addAthlete() async {
// //   if (_formKey.currentState!.validate()) {
// //     if (_imageFile != null) {
// //       String imageUrl = await _uploadImage(_imageFile!);
// //       if (imageUrl.isNotEmpty) {
// //         Athlete newAthlete = Athlete(
// //           id: '',  // Assuming ID is not needed or generated by Firestore
// //           firstName: _firstNameController.text.trim(),
// //           lastName: _lastNameController.text.trim(),
// //           nationalId: _nationalIdController.text.trim(),
// //           gender: _gender,
// //           age: int.tryParse(_ageController.text) ?? 0,
// //           phoneNumber: _phoneNumberController.text.trim(),
// //           profilePic: imageUrl,
// //         );
// //         await FirebaseFirestore.instance.collection('athletes').add(newAthlete.toMap());
// //         Navigator.pop(context);
// //       } else {
// //         print('Failed to get image URL');
// //       }
// //     } else {
// //       print('No image selected');
// //     }
// //   }
// // }


// //   @override
// //   Widget build(BuildContext context) {
// //     return Scaffold(
// //       appBar: AppBar(
// //         title: Text('Add New Athlete'),
// //       ),
// //       body: SingleChildScrollView(
// //         padding: EdgeInsets.all(16),
// //         child: Form(
// //           key: _formKey,
// //           child: Column(
// //             children: [
// //               GestureDetector(
// //                 onTap: _pickImage,
// //                 child: CircleAvatar(
// //                   radius: 60,
// //                   backgroundColor: Colors.grey[200],
// //                   backgroundImage: _imageFile != null ? FileImage(_imageFile!) : null,
// //                   child: _imageFile == null ? Icon(Icons.camera_alt, size: 50) : null,
// //                 ),
// //               ),
// //               TextFormField(
// //                 controller: _firstNameController,
// //                 decoration: InputDecoration(labelText: 'First Name'),
// //                 validator: (value) {
// //                   if (value!.isEmpty) return 'Please enter first name';
// //                   return null;
// //                 },
// //               ),
// //               TextFormField(
// //                 controller: _lastNameController,
// //                 decoration: InputDecoration(labelText: 'Last Name'),
// //                 validator: (value) {
// //                   if (value!.isEmpty) return 'Please enter last name';
// //                   return null;
// //                 },
// //               ),
// //               TextFormField(
// //                 controller: _nationalIdController,
// //                 decoration: InputDecoration(labelText: 'National ID'),
// //                 validator: (value) {
// //                   if (value!.isEmpty) return 'Please enter national ID';
// //                   return null;
// //                 },
// //               ),
// //               TextFormField(
// //                 controller: _phoneNumberController,
// //                 decoration: InputDecoration(labelText: 'Phone Number'),
// //                 validator: (value) {
// //                   if (value!.isEmpty) return 'Please enter phone number';
// //                   return null;
// //                 },
// //               ),
// //               TextFormField(
// //                 controller: _ageController,
// //                 decoration: InputDecoration(labelText: 'Age'),
// //                 keyboardType: TextInputType.number,
// //                 validator: (value) {
// //                   if (value!.isEmpty) return 'Please enter age';
// //                   if (int.tryParse(value) == null) return 'Please enter a valid age';
// //                   return null;
// //                 },
// //               ),
// //               DropdownButtonFormField<String>(
// //                 value: _gender,
// //                 onChanged: (newValue) {
// //                   setState(() {
// //                     _gender = newValue!;
// //                   });
// //                 },
// //                 items: ['Male', 'Female']
// //                     .map<DropdownMenuItem<String>>((String value) {
// //                   return DropdownMenuItem<String>(
// //                     value: value,
// //                     child: Text(value),
// //                   );
// //                 }).toList(),
// //                 decoration: InputDecoration(labelText: 'Gender'),
// //               ),
// //               SizedBox(height: 20),
// //               ElevatedButton(
// //                 onPressed: _addAthlete,
// //                 child: Text('Add Athlete'),
// //               ),
// //             ],
// //           ),
// //         ),
// //       ),
// //     );
// //   }
// // }




// import 'package:flutter/material.dart';
// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:judging_app/models/Athlete.dart';

// class AddAthleteScreen extends StatefulWidget {
//   @override
//   _AddAthleteScreenState createState() => _AddAthleteScreenState();
// }

// class _AddAthleteScreenState extends State<AddAthleteScreen> {
//   final TextEditingController _firstNameController = TextEditingController();
//   final TextEditingController _lastNameController = TextEditingController();
//   final TextEditingController _nationalIdController = TextEditingController();
//   final TextEditingController _genderController = TextEditingController();
//   final TextEditingController _ageController = TextEditingController();
//   final TextEditingController _phoneNumberController = TextEditingController();

//   @override
//   void dispose() {
//     _firstNameController.dispose();
//     _lastNameController.dispose();
//     _nationalIdController.dispose();
//     _genderController.dispose();
//     _ageController.dispose();
//     _phoneNumberController.dispose();
//     super.dispose();
//   }

//   void saveAthlete() async {
//     FirebaseFirestore firestore = FirebaseFirestore.instance;
//     Athlete athlete = Athlete(
//       id: DateTime.now().millisecondsSinceEpoch.toString(),
//       firstName: _firstNameController.text,
//       lastName: _lastNameController.text,
//       nationalId: _nationalIdController.text,
//       gender: _genderController.text,
//       age: int.tryParse(_ageController.text) ?? 0,
//       phoneNumber: _phoneNumberController.text,
//       profilePic: '', // Placeholder, replace with actual path if needed
//       trainerPhone: '', // Add logic to get trainer's phone number
//     );

//     try {
//       await firestore.collection('athletes').doc(athlete.id).set(athlete.toMap());
//       Navigator.pop(context);
//     } catch (e) {
//       print("Error saving athlete: $e");
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('Add New Athlete'),
//       ),
//       body: SingleChildScrollView(
//         padding: EdgeInsets.all(16.0),
//         child: Column(
//           children: <Widget>[
//             TextField(
//               controller: _firstNameController,
//               decoration: InputDecoration(labelText: 'First Name'),
//             ),
//             TextField(
//               controller: _lastNameController,
//               decoration: InputDecoration(labelText: 'Last Name'),
//             ),
//             TextField(
//               controller: _nationalIdController,
//               decoration: InputDecoration(labelText: 'National ID'),
//             ),
//             TextField(
//               controller: _genderController,
//               decoration: InputDecoration(labelText: 'Gender'),
//             ),
//             TextField(
//               controller: _ageController,
//               decoration: InputDecoration(labelText: 'Age'),
//               keyboardType: TextInputType.number,
//             ),
//             TextField(
//               controller: _phoneNumberController,
//               decoration: InputDecoration(labelText: 'Phone Number'),
//             ),
//             SizedBox(height: 20),
//             ElevatedButton(
//               onPressed: saveAthlete,
//               child: Text('Save Athlete'),
//             ),
//           ],
//         ),
//       ),
//     );
//   }
// }

